name: 404 links

on: [push]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'restqa-404-links'
      uses: restqa/404-links@v1.0.1
      with:
        ignore: 'https://www.linkedin.com/company/restqa,https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks'
